# Select image for build machine
image: ubuntu

# Test against the latest version of this Node.js version
environment:
  nodejs_version: "8"

# Pre-install init script
init:
  - node --version
  - npm --version

# Install scripts. (runs after repo cloning)
install:
  - cd botbuilder-teams-js
  - npm install

# Post-install build scripts.
build_script:
  - npm run build

# Post-install test scripts.
test_script:
  - npm run test
