# Select image for build machine
image: ubuntu

# Test against the latest version of this Node.js version
environment:
  nodejs_version: "8.11.3"
  project_folder: "botbuilder-microsoftteams-node"

# Pre-install init script
init:
  - rm -rf /home/appveyor/projects/$project_folder
  - mkdir /home/appveyor/projects/$project_folder
  - nvm install $nodejs_version
  - nvm use $nodejs_version
  - node --version
  - npm --version

# Install scripts. (runs after repo cloning)
install:
  - cd botbuilder-teams-js
  - npm install

# Post-install build scripts.
build_script:
  - npm run build

# Post-install test scripts.
test_script:
  - npm run test
